languages: python
python:
  - "3.7"

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - cd frontend && yarn install

before_script:
  - psql -c 'create database test_db;' -U postgres
  - cd frontend && yarn build

script:
  - cd backend && python manage.py migrate && python manage.py test
