# Generated by Django 3.0.4 on 2020-03-08 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmgr', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='accounttype',
            name='name',
            field=models.CharField(choices=[('CC', 'Credit Card'), ('DC', 'Debit Card'), ('CASH', 'Cash')], max_length=4, unique=True),
        ),
        migrations.AlterField(
            model_name='expensetype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='institution',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='end_time',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='rewardtype',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
