# Generated by Django 3.0.4 on 2020-03-08 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmgr', '0006_auto_20200308_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='alias',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.CharField(max_length=20),
        ),
    ]
