# Generated by Django 3.0.4 on 2020-04-02 04:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmgr', '0008_auto_20200402_0410'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='budgetmgr.Account'),
        ),
    ]
