# Generated by Django 3.0.4 on 2020-04-05 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('budgetmgr', '0009_auto_20200402_0411'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='create_date',
            new_name='create_time',
        ),
    ]
